### ISSUE TITLE
Crash when filter refers to custom database field 

### ISSUE THREAD

**Issue by OdinGitDat** [reupen/columns_ui#133]
Not sure if foo_customdb is still supposed to be supported by cui 1.0, I hope so. But when a filter that refers to a custom database field loads, the entire client crashes.

The variables work fine when used anywhere else like main window title and status bar and pane.

I am on 1.0 alpha 2

**Comment by reupen** [comment]
The main thing that's changed there would be threading so it may be that foo_customdb is not thread-safe. The relevant interface in the foobar2000 SDK requires thread safety so that would be a bug in foo_customdb.

Have you submitted a crash log? If so, I'll have a look at it later (it may not reveal much, though).

If you run the component troubleshooter is foo_customdb listed?

**Comment by OdinGitDat** [comment]
[Ah yes you're right](http://help.foobar2000.org/problem/e8b4852e5484044bc8c13e5a9db3ad36), likely customdb doesn't support threading. That's a shame cause customdb doesn't seem to be under active development. Guess I'll have to stick with cui 0.5.1

**Comment by reupen** [comment]
Looking at the crash that was submitted since my last message, I'm afraid there's not too much I can glean from it as it shows Custom Database crashing while Columns UI was formatting the title of a track. 

The recent events also make it sound like threading problems:

```
Recent events:
Custom Database: not an error (21)
Custom Database: not an error (21)
Custom Database: not an error (21)
Custom Database: not an error (21)
Custom Database: unknown error (21)
Custom Database: library routine called out of sequence (21)
Custom Database: library routine called out of sequence (21)
Custom Database: unknown error (21)
Custom Database: library routine called out of sequence (21)
Custom Database: not an error (21)
Custom Database: not an error (21)
Custom Database: not an error (21)
Custom Database: unknown error (21)
Custom Database: library routine called out of sequence (21)
Custom Database: not an error (21)
Custom Database: not an error (21)
Custom Database: library routine called out of sequence (21)
Custom Database: not an error (21)
Custom Database: library routine called out of sequence (21)
Custom Database: library routine called out of sequence (21)
Custom Database: unknown error (21)
Custom Database: not an error (21)
Custom Database: not an error (21)
Custom Database: library routine called out of sequence (21)
Custom Database: unknown error (21)
Custom Database: unknown error (21)
Custom Database: library routine called out of sequence (21)
Custom Database: library routine called out of sequence (21)
Custom Database: not an error (21)
Custom Database: library routine called out of sequence (21)
```

Those errors are from SQLite, and although it's an old page, this page gives a good explanation of 'library routine called out of sequence':
https://www.sqlite.org/cvstrac/wiki?p=LibraryRoutineCalledOutOfSequence

And the general meaning of code 21 is explained here:
https://www.sqlite.org/rescode.html#result_code_meanings

Lastly there are a number of crashes from Custom Database at the same address going back over a period of time.

So, as you probably already gathered, there isn't much I can do about this I'm afraid.
