### ISSUE TITLE
item properties panel + track_property_provider_v2

### ISSUE THREAD

**Issue by marc2k3** [reupen/columns_ui#249]
I maintain 2 components which implement track_property_provider_v2 and these display OK in the Properties dialog like this...

![Untitled](https://user-images.githubusercontent.com/34617027/68110722-6bbc9e00-fee5-11e9-8c0a-b95515793402.png)

The item properties panel in CUI 0.5.1 does display them but doesn't recognise the different group names...

![051](https://user-images.githubusercontent.com/34617027/68111071-32386280-fee6-11e9-9f16-161c5da4e116.png)

CUI 1.2.0 doesn't recognise them at all...

![120](https://user-images.githubusercontent.com/34617027/68111072-32386280-fee6-11e9-82a9-f6c0c67eddd2.png)

It's quite possible I'm doing something wrong but the code was lifted pretty much as-is from foo_sample included with the SDK! I did try updating track_property_provider_v2 to track_property_provider_v3 but that hasn't made any difference.

**Comment by reupen** [comment]
Hi,

That wasn't really intentional, I hadn't realised that 0.5.1 was bunging unknown groups into 'Other'.

What happened is that I observed in a local configuration that Item properties was fairly slow at updating, and some track property providers from JScript panel were particularly slow. As part of fixing that, I stopped the code from loading properties for unknown track property groups.

To add to the confusion, unlike the Properties dialogue, the selection properties element in DUI seems to put properties from unknown groups under 'Other'.

The problem seems to be that the foobar2000 API doesn't give a way to enumerate groups by themselves, and hence implementing settings to hide and show particular groups is difficult.

I'll have a look at reinstating unknown groups for 1.3.0. (I'll need to have a look at what the best way to do that is given the above; it may be that, in Item properties options, unknown groups are controlled by something like 'All other groups', but the panel itself displays the correct group titles.)

If JScript panel could also look at implementing track_property_provider_v4 (and ensuring those providers are thread-safe), that would also be helpful.

Thanks

**Comment by marc2k3** [comment]
If JSP is the cause of slowdowns then I'd be happy enough just seeing the info for a selection count of 1. That's the only time output detailed info anyway. Any selection of more than one is just an aggregate of the playcounts which I'm not that bothered about...

https://github.com/marc2k3/foo_jscript_panel/blob/0f24724d4a02a353a510471d8c5ea1216f9a4297/src/stats.cpp#L109-L152

**Comment by reupen** [comment]
Yes, changing that in JScript Panel would presumably fix that performance problem.

Selection properties in the Default UI doesn't seem to show its 'Other' group by default either; most probably, I'll change the Item properties default settings to match.

**Comment by marc2k3** [comment]
I've implemented track_property_provider_v4 so I'll close this.

https://github.com/marc2k3/foo_jscript_panel/commit/9b000af64cbb6b80c4ee1ef70cd37a6205478dd9

I've tested it plays nice on fb2k v1.4.8 where it's unavailable and it seems fine.
