### ISSUE TITLE
Suggestion - Show the first line of the UNSYNCED LYRICS tag instead of .

### ISSUE THREAD

**Issue by stephen147** [reupen/columns_ui#307]
See here in the properties panel.

The **UNSYNCED LYRICS** gets shown as . when the first line is not that.

Maybe a way to show this? Thanks.

![R0PitWG2UF](https://user-images.githubusercontent.com/14054664/79924561-f5c6d780-842f-11ea-9bea-6cad61868e46.png)

**Comment by reupen** [comment]
As you might know, foobar2000 itself suppresses the loading of lyrics (to reduce memory usage). 

To bypass that, the panel would potentially need to read the metadata of a large number of tracks (depending on how many are selected and have suppressed metadata). Hence, I don't think Item properties is a good candidate for doing that (also as it can't display full lyrics anyway).

I think displaying the first line instead of `.` would be a request for foobar2000 itself. However, you could edit `LargeFieldsConfig.txt` in your foobar2000 configuration folder so that lyrics are always loaded, or you can use e.g. Item details to display lyrics since that should show them in most cases.

**Comment by stephen147** [comment]
After editing the file and removing `fieldSpam=unsynced lyrics` bit it has no effect on the `.` after restarting foobar. Is it suppose to?

**Comment by reupen** [comment]
The limits at the top also apply – you'll probably want add a `fieldBasic` for it and increase `basicMetaMax` to a larger number.

**Comment by stephen147** [comment]
Hi,

When I do that what you suggested I get this.

Notice the weird overlapping on the unsynced lyrics value.

![image](https://user-images.githubusercontent.com/14054664/80962536-20883700-8e05-11ea-9f95-c8c204b02c28.png)

The Unsynced Lyric tags contains.
```
Release type:		Release
----------------------------------------------
Exclusive to beatport:	No
----------------------------------------------
RDNK does not have a nationality or race; its not even a human, because it does not possess a body yet. It is an astral force of the universe. On its way to Earth RDNK has been creating music in order to communicate with humans in a universal language. To make this music palpable for humans, RDNK took the best fitting parts from their past music and included them into a new sound. The outcome can be called Future Techno.
----------------------------------------------
Tagged by:		Mp3Tag w/ beatport.com scripts [v4.4 by stevehero™] (◣_◢) (http://bit.ly/2EmyidV)
```

**Comment by reupen** [comment]
That looks like a bug. Could you open a separate issue for it?

**Comment by stephen147** [comment]
Done. 

https://github.com/reupen/columns_ui/issues/313
