### ISSUE TITLE
Suggestion - Show number of selected items in status bar

### ISSUE THREAD

**Issue by m0vie** [reupen/columns_ui#315]
I miss the feature to show the number of selected items in the status bar.

I am currently compiling my own plugin and hijack the "Shot total length of selected tracks" option with the following diff:
``` diff
diff --git a/foo_ui_columns/status_bar.cpp b/foo_ui_columns/status_bar.cpp
index 7987682..ddb4730 100644
--- a/foo_ui_columns/status_bar.cpp
+++ b/foo_ui_columns/status_bar.cpp
@@ -190,6 +190,12 @@ void get_selected_length_text(pfc::string_base& p_out, unsigned dp = 0)
     length = sels.calc_total_duration();

     p_out = pfc::format_time_ex(length, dp);
+       p_out.add_string("    ");
+       p_out.add_string(pfc::format_int(count));
+       p_out.add_string(" track");
+       if (count != 1) {
+               p_out.add_string("s");
+       }
 }
```

![image](https://user-images.githubusercontent.com/1491108/84179345-18678b00-aa86-11ea-9244-2d2483b413a9.png)

This is a bit crude - a separate option for it would be much nicer.

But this would mean adding new preferences / ui elements / adapt size calculation, which are not that straight-forward as a non-c++ developer.

**Comment by Isabelxxx** [comment]
+1 
on DUI, the total number of selected items is also visible on the items properties panel. Whether it is on the status bar or both, it would be a great addition. 

Also note that while the status panel shows that number, it can not be neither configurable like the status bar nor resized (one line bar size instead of 2)... right clicking is not working too. So we get 2 bars/panels supposed to do the same thing but having different features (?)
