### ISSUE TITLE
Question - can splitter children see when they're hidden

### ISSUE THREAD

**Issue by sammoth** [reupen/columns_ui#342]
Hi, I built the foo_uie_example panel and tried it in some layouts. When the panel is in a tab, switching to/from the tab sends a WM_SHOWWINDOW message to the example panel. However if the example panel is within a splitter inside a tab page, it only receives WM_SHOWWINDOW once when it's first shown. After that it receives no messages when it's being hidden. Is there any way for a child to be notified when it's in a splitter and it's hidden?

**Comment by reupen** [comment]
Hi,

I don't think there's a simple way to be notified in that situation, unfortunately. You should be able to [use `IsWindowVisible()`](https://docs.microsoft.com/en-gb/windows/win32/api/winuser/nf-winuser-iswindowvisible) to determine the current state, though. Could that be made to work? Are you trying to optimise performance when the panel isn't visible?

The only way I can think of to be notified is to use a message hook and check if any `WM_SHOWWINDOW` messages received are targetted at a parent window.

I think that could be done using foobar2000's [`message_filter` mechanism](https://github.com/reupen/foobar2000-sdk-modified/blob/master/SDK/message_loop.h). (From memory, it misses messages when modal windows are open or a blocking function has its own message loop, but that's probably not a big problem here. The more comprehensive option is to use a [WH_GETMESSAGE hook](https://docs.microsoft.com/en-gb/windows/win32/winmsg/about-hooks#wh_getmessage), but it's a bit more complicated.) 

However, there would be some complexity (consider that a parent window high in the hierarchy could be shown, but a window lower in the chain could still be hidden. So, I suspect it may not be worth the effort. (Also, if you do go down this route, be careful to only observe messages and not stop any from being processed or otherwise interfere with other windows.)

**Comment by sammoth** [comment]
Thank you for the reply!

Yes I'm trying to keep a video from playing when it's not visible. Polling IsWindowVisible() would be reasonable as it would only be done when a video is playing anyway, that was the only way I could think to do it. I didn't know about the `message_filter` mechanism, I'll have a look at that. It will be simple for me to recover the correct state if a message is missed.

**Comment by sammoth** [comment]
I tried each option. It seems `message_filter` and even `WH_GETMESSAGE` hook don't receive the SHOWWINDOW message even if requesting messages from all threads. In the end I had to hook WH_CALLWNDPROCRET to get the SHOWWINDOW message. I will stick to just polling IsWindowVisible for my purposes, implementing the hook didn't make that much difference to responsiveness.
