### ISSUE TITLE
File operations context menu not working on custom buttons

### ISSUE THREAD

**Issue by regorxxx** [reupen/columns_ui#378]
https://hydrogenaud.io/index.php?topic=121212.new#new
The gif is pretty explicative. None of the file operations menu entries work as buttons.
foobar 1.5.6 (some days ago tried it on a more recent installation with same results)
![error3](https://user-images.githubusercontent.com/83307074/123424302-2e23f180-d5b0-11eb-9d2e-08215422b478.JPG)
![bug](https://user-images.githubusercontent.com/83307074/123424458-6297ad80-d5b0-11eb-9d7c-b1ea53233211.gif)

Have been told it may be a CUI bug, since I use CUI and it works on DUI. The context menu work without problems, it's just the button the one not working.

**Comment by reupen** [comment]
Could you confirm what version of Columns UI you're using?

The command should show as 'File Operations/Move to/...', rather than just 'File Operations/Move to' (with everything up to date):

![image](https://user-images.githubusercontent.com/12693549/123454037-047ec080-d5d8-11eb-97e4-d2f9b95ea370.png)

(Older versions of Columns UI did indeed have some bugs in relation to this.)

**Comment by regorxxx** [comment]
1.6.0
But definitely I'm not seeing the same menus than you!

Note I use foobar 1.5.6, not the latest version. Don't know if those menus come from CUI or foobar, but it may be that the latest CUI version is not working with the old menus   (?)

**Comment by regorxxx** [comment]
Ups. Clicked on the wrong button

**Comment by reupen** [comment]
OK, I can reproduce with old versions of foobar2000.

I'll have a look at why it's not working there.
