### ISSUE TITLE
Artwork panel switches artwork type even locked

### ISSUE THREAD

**Issue by regorxxx** [reupen/columns_ui#380]
On latest build:

![bug8](https://user-images.githubusercontent.com/83307074/123554942-23b15580-d772-11eb-83eb-f08bd4aefc7e.gif)

The check menu does not change after clicking on the panel though. And multiple clicking does not cycle, once it switches from front, can not be reverted back (unless the menu is used to select front).

**Comment by reupen** [comment]
Thanks for testing and for the report 🙂 

I'll have a look.

**Comment by reupen** [comment]
I've just merged a fix for the problem you observed where clicking on the artwork view panel resulted in it being stuck on the stub image.

Other than that, Lock artwork type doesn't prevent clicking on the panel, it only stops the panel automatically falling back to a different artwork type if the selected one isn't available (the behaviour when locked should be the same as 1.6.0).

Feel free to retest and let me know if you still see anything wrong.

I'll have a separate look at improving the Reload artwork command so that it's a bit more forceful in reloading.

**Comment by regorxxx** [comment]
Seems to work perfectly now. So it's solved.

Thanks!
