### ISSUE TITLE
Delete toolbar

### ISSUE THREAD

**Issue by grimes2** [reupen/columns_ui#402]
It's dangerous to delete the CUI toolbar with (rightclick in toolbar) "Delete toolbar". Beginners don't know, how to revert. A second row toolbar is deleted completely (no revert possible). Please add a confirmation message: This will delete the toolbar. To revert:  Ctrl+P | Display | ColumnsUI | Show Toolbars

**Comment by reupen** [comment]
To get stuck via that context menu item, someone would need to manually remove each toolbar individually. But yes, if it's the last toolbar being removed, it could do something more useful. This applies to whether they use 'Remove toolbar', or simply untick the last toolbar.

Show toolbars will be useless once this is done. The only way out would be 'Reset toolbars'.

Perhaps you were referring to the 'View/Show toolbars' main menu item rather than the 'Remove toolbar' context menu item?

**Comment by grimes2** [comment]
I was wrong. The context menu command "Remove toolbar" removes only  the individual (single) toolbar, and not the complete toolbars. I don't think, that a user removes all toolbars. The problem is probably "View/Show toolbars", because that removes all toolbars (also the menu toolbar). You need to use the shortcut Ctrl+P to revert. To add a confirmation message would be nice.

**Comment by reupen** [comment]
I think that menu item can simply be hidden – I can't see any reason someone would need to use it on a frequent basis.

**Comment by grimes2** [comment]
That's a solution. Background: A beginner user in German foobar2000 Forum accidentally removed all toolbars and couldn't revert.
