### ISSUE TITLE
DarkMode menus & popup dialogs

### ISSUE THREAD

**Issue by marc2k3** [reupen/columns_ui#416]
When you open the native fb2k playlist manager or album list and right click, they inherit the dark menus from CUI. Not entirely terrible but probably not desirable either.

But of course I'm special and have a worse issue with my component's configuration window.

See these entries are dark...

![Untitled](https://user-images.githubusercontent.com/62050527/148427559-636d1a46-6d35-4723-8454-80b9dd03d698.png)

But the other menus are not.

![Untitled1](https://user-images.githubusercontent.com/62050527/148427563-631235c7-9c6b-415d-ad3b-87fea6b0b218.png)

I suspect the reason for this discrepancy is that the File menu entries are hard coded inside my `rc` file here

https://github.com/marc2k3/foo_jscript_panel/blob/e796f8bf875897290dadacd20692b1eb05a2969b/src/Resource/foo_jscript_panel.rc#L16-L23

but all the other menus are dynamically generated inside my OnInitDialog from scanning the contents of various folders for text files and generating the menu entries based on their names...

https://github.com/marc2k3/foo_jscript_panel/blob/e796f8bf875897290dadacd20692b1eb05a2969b/src/UI/DialogConfigure.cpp#L95-L147

Not sure what can be done but I thought I'd report it anyway.

**Comment by reupen** [comment]
> When you open the native fb2k playlist manager or album list and right click, they inherit the dark menus from CUI. Not entirely terrible but probably not desirable either.

Yep – the flag that controls this is process-wide, unfortunately. Even Windows Explorer has the same problem:

![image](https://user-images.githubusercontent.com/12693549/148442734-720baa15-c587-47fd-9ca8-af891f84609d.png)

Dark mode is probably going to be disabled by default so it'll be up to a user to decide if they want to use it (understanding limitations, such as that third-party panels may not support it). (In theory a separate toggle to control the process-wide changes could also be added if it turns out there's a good case for it...)

> But of course I'm special and have a worse issue with my component's configuration window.

Hmm, that is annoying. I haven't found anything that I can change on my side to make the other menus dark, unfortunately. (But, in reality, many panels will need updating to support dark mode anyway.)

**Comment by marc2k3** [comment]
I had no idea about explorer. I find the overall implementation in windows 10 horrible so I never enable it.

I might as well close this and see what happens on final release and see if there is anything I can copy/paste!

**Comment by marc2k3** [comment]
Well it seems I must have at least one hardcoded entry in my rc before I can call ATL's GetMenu so I've made a dummy entry, remove it on init and then add a new File menu in the same way I've added my other entries. Problem solved.

https://github.com/marc2k3/foo_jscript_panel/commit/110c8219534aa2f87ca5a97d98c15948c0d08022
