### ISSUE TITLE
Add ability to set custom icon size in buttons toolbar

### ISSUE THREAD

**Issue by a1waysbeta** [reupen/columns_ui#421]
Is it possible to add symbol font support to the control buttons? Similar to win10 groove player control bar

**Comment by reupen** [comment]
Hi,

I'm not entirely sure what is being referred to (in Groove Music or Columns UI).

Starting with Groove Music, do you mean the main controls:

![image](https://user-images.githubusercontent.com/12693549/149215716-e975a942-0690-4789-b419-a39a80cb68ef.png)

Or the taskbar controls:

![image](https://user-images.githubusercontent.com/12693549/149215920-d87e36f7-5686-452d-b2d3-b102c6c2e471.png)

Or something else? 

Thanks

**Comment by a1waysbeta** [comment]
Sorry, poor presentation. I mean the first screenshot above. When selecting Icon symbols, you can select fonts and support resizing.

**Comment by a1waysbeta** [comment]
'There's a particular font I'd like to use for buttons ' or 'I'd like SVG support for buttons' . That's what I'm trying to say, so that you can use the icons contained in the existing font directly, and furthermore, you can set the icon size

**Comment by reupen** [comment]
I'm afraid using font characters or SVGs for icons is unlikely to be implemented due to the complexity involved, and I'm not convinced doing it with fonts is a good idea anyway.

However, `.ico` files can contain images in multiple sizes, and that usually works well enough. Being able to set a custom size for icons is currently missing, though, so let's make this issue about that.

**Comment by a1waysbeta** [comment]
It would be perfect if it was possible to set the size of the icons. the current icon bar is a bit small.
