### ISSUE TITLE
[dev build] taking over DUI colours in themed mode

### ISSUE THREAD

**Issue by marc2k3** [reupen/columns_ui#578]
It has this rather unfortunate side effect...

![image](https://user-images.githubusercontent.com/62050527/188322552-9c0944ef-a830-4dc2-900c-2cf17738b528.png)

And the reason I use themed mode is because of the consistent barely visible line separators in selection properties and playlist group headers as shown above.

If you use one of the other modes, you end up with different group header lines like this (maybe this should have been a separate issue 😀  )

![image](https://user-images.githubusercontent.com/62050527/188322640-6e5f29f0-0315-49c5-a12c-daba4d7b52b2.png)

Love the whole idea though. I think I'll be using ui_config_callback and ditching all common_callback stuff in my component.

**Comment by reupen** [comment]
Thanks – that was a last minute change I made to the return value of `ui_config_manager::query_color()` (which I must've not tested in dark mode...) Fix coming soon...

> If you use one of the other modes, you end up with different group header lines like this (maybe this should have been a separate issue 😀 )

Yes, intentional, unfortunately. In themed mode, that colour comes from the visual style, but in non-themed mode it doesn't have that available, so just uses the text colour.

**Comment by reupen** [comment]
Should be resolved in the latest build (if you want to check things again...)

**Comment by marc2k3** [comment]
Looking good, thanks.
