### ISSUE TITLE
Missing 'Play' on contextual menu

### ISSUE THREAD

**Issue by regorxxx** [reupen/columns_ui#662]
Play is missing on the contextual menu even if it's enabled (and shift doesn't show it).
![imagen](https://user-images.githubusercontent.com/83307074/217201466-dddf8301-4f45-4e67-9f07-b99ae2acc667.png)
![imagen](https://user-images.githubusercontent.com/83307074/217201552-8f91488e-9397-43ce-816d-d74e3cab7089.png)

On foobar 1_6 and v2.
![imagen](https://user-images.githubusercontent.com/83307074/217201591-9f3a2df7-a6e8-41bf-b28a-735e3fc49e8c.png)

**Comment by reupen** [comment]
It's not obvious but the Play item in context menu preferences affects non-playlist context menus only (e.g. Playlist search).

Play is missing from the playlist view context menu because the UI is expected to add it, as far as I can see. Will mark this as a bug as even the Playlist switcher panel has it.
