### ISSUE TITLE
Play current playlist

### ISSUE THREAD

**Issue by regorxxx** [reupen/columns_ui#663]
As noted in this thread:
https://hydrogenaud.io/index.php/topic,123659.new.html#info_1022258

There is no way to force foobar2000 to play from active playlist without some other conditional settings or using the mouse to double click on a track.  'Playback/Play from current playlist'

Apart from accessibility concerns, it would be great to have a 'Play current playlist' entry, to be able to use it on CMD or other scripts.

**Comment by reupen** [comment]
All playback and playlist state is managed by the foobar2000 core and works independently of the active UI. Therefore, it doesn't make sense to implement such a command directly in Columns UI (or otherwise for Columns UI alter playback behaviour).

So the functionality belongs in either a separate third-party component, or the foobar2000 core itself, I'm afraid.
