### ISSUE TITLE
Reduce flash of loading state when manually playing a track

### ISSUE THREAD

**Issue by reupen** [reupen/columns_ui#713]
When a track is playing, if another (or the same) track is manually played there can be a brief flash of loading state in various parts of the UI. If the new track loads very quickly, this flash of the loading state is not particularly helpful, and could be avoided.

See https://github.com/reupen/columns_ui/discussions/711 for discussion.

**Comment by reupen** [comment]
On further investigation, there is a slight delay introduced when the taskbar buttons are being updated following playback status changes. This is the cause of the difference in behaviour between Columns UI and Default UI.

**Comment by Sneakpeakcss** [comment]
@reupen 

_I started testing some of the new features/changes and found some unexpected behaviour regarding this._

 

First of all… The flashes barely ever show up now, it even looks like it's in a better state than the vanilla foobar, so that's really great!

However i think i managed to find a possible bug/oversight:

Changing a track manually by either LMB or using `CUI Buttons Toolbar` works flawlessly, but doing the same using `JScript Panel` presents the same flashing behaviour as previously.
I'm not exactly sure how `JScript` handles those buttons (`fb.Play()` / `fb.Prev()` / `fb.Next()`), but it seems that it's a shared behaviour with the default foobar options in `Playback` menu:



https://github.com/reupen/columns_ui/assets/77424331/6ad45a87-3d42-4268-a1c4-50626d101cfd

00:00 `LMB:` ✔️
00:05 `CUI Buttons:` ✔️
00:10 `JScript Buttons:` ❌
00:22 `Foobar Menu (Manually):` ❌
00:43 `Foobar Hotkeys assigned to the same menu options (Previous / Next):` ✔️

Surprisingly it works when using hotkeys, but not when manually used through menu, i assume that `JScript` isn't the one at fault here and it just shares the same issue source.

**Comment by reupen** [comment]
I assume your menu is using auto-hide – is there any difference if it isn't? How do the two bad cases behave in Default UI?

**Comment by Sneakpeakcss** [comment]
Removing auto-hide didn't help. In case of Default UI it's a bit hard to tell:
 

https://github.com/reupen/columns_ui/assets/77424331/f525f6fb-08a1-4658-a534-55e3ad4f4c18


`DUI Buttons` / `JScript` / `Foobar menu (Manually)` seem to have the same speed, with JScript _maybe_ being slightly slower(??), but it's on such a level that i cannot really tell the difference between them. Using hotkeys (not shown on video) has the same behaviour where it doesn't flash at all.

**Comment by reupen** [comment]
Thanks, I was able to reproduce it with Default UI. I understand there'll be a universal fix in an upcoming version of foobar2000 (the next preview build I assume), so have a look out for that.

**Comment by reupen** [comment]
@Sneakpeakcss That new foobar2000 preview build is now available: https://www.foobar2000.org/download

**Comment by Sneakpeakcss** [comment]
Funny enough i tested it a moment ago and was just now typing a message to confirm that it works perfectly on preview, even with the pre-fix CUI build.
