### ISSUE TITLE
a border around the text when i use color the text only

### ISSUE THREAD

**Issue by JohnnyFireOne** [reupen/columns_ui#751]
a border around the text when i use color the text only on labumlist panel and on playlistview
i use latest albumlist panel and columsui and happends too in dev builds

may i ask for a fix or and option to make more tweakable if its by design?

![250413134-58a1fc61-29e0-400b-9d67-b9c7abb859c2](https://github.com/reupen/columns_ui/assets/136648679/7873339b-8e48-43a6-9c8f-2e65e0d5887d)
![250413903-a0fd0c36-2df7-45fb-813e-2058e491a490](https://github.com/reupen/columns_ui/assets/136648679/ba4e9d1c-e1db-4897-86ac-96b9eb16ea86)

**Comment by reupen** [comment]
That is a focus rectangle. It's displayed in the playlist view if it's focused and any of the following are true:

- you have pressed certain keyboard keys
- 'Use custom active item frame' is enabled in Colours and fonts preferences
- 'Playback follows cursor' is enabled

It's by design that it's displayed as it's needed for navigation. You can change the colour of it in the playlist view if you enable 'Use custom active item frame' (alas, there seems to be a bug there in themed mode, but that's a separate issue).

There is no customisation of it in Album list panel as the Windows tree view control is rendering it.
