### ISSUE TITLE
Segoe Fluent Icons in Use custom title (Layout)

### ISSUE THREAD

**Issue by grimes2** [reupen/columns_ui#835]
Adding Segoe Fluent Icons to Preferences | Columns UI | Layout | Use custom title results in a point in the input
box. Is it possible to display the icon in the inputbox?

![Screenshot 2023-12-25 024150](https://github.com/reupen/columns_ui/assets/15456836/22a3f135-35ee-4a7b-9531-744eeaf37b5e)

**Comment by reupen** [comment]
Did you configure the tabs to use Segoe Fluent Icons as the font? Since they aren't standard Unicode characters (rather 'private use' ones), that edit box will need to use the same font. So the solution is probably going to be to make it possible to configure the font used for that edit box...

**Comment by grimes2** [comment]
I didn't configure the tabs, they are displaying the font out of the box.

**Comment by reupen** [comment]
Copy and paste some examples of characters that aren't and are displaying here, and also confirm what font is listed for Tab stack on the fonts page.

**Comment by grimes2** [comment]
Everything before U+E2F7 is displayed correctly.

![Screenshot 2023-12-25 111430](https://github.com/reupen/columns_ui/assets/15456836/3b407039-105b-4f38-9f38-0c34a2584543)

**Comment by reupen** [comment]
The Fluent icons start from E700: https://learn.microsoft.com/en-us/windows/apps/design/style/segoe-fluent-icons-font#using-the-icons

The ones that are displaying correctly are in Segoe UI Symbol, which will display correctly in most places due to [font linking](https://learn.microsoft.com/en-us/globalization/fonts-layout/fonts#font-linking-and-gdi).

If you really want, you could try adding Segoe Fluent Icons (in the correct format) to the entries for Tahoma and Segoe UI at `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\FontLink\SystemLink`. (Restart, and hopefully they'll display in most places).

Otherwise, the font preferences screenshot confirms that Segoe Fluent Icons is configured as the font, so it's back to being able to configure the font used in that edit box...
