### ISSUE TITLE
Option to remove playlist in playlist selector

### ISSUE THREAD

**Issue by grimes2** [reupen/columns_ui#839]
Please add the option remove playlist in the toolbar context menu of playlist selector.

**Comment by grimes2** [comment]
There is already a shortcut for remove current playlist: Ctrl+W or [Shift] File | Remove playlist. So you don't need to implement. Is it possible to make a playlist or autoplaylist read only in Playlist Switcher?

**Comment by reupen** [comment]
A playlist lock has a particular meaning in the foobar2000 API. It essentially means a particular component has control over that playlist in some way. An autoplaylist is a type of playlist lock.

In theory, the playlist switcher could implement a playlist lock that doesn't allow that playlist to be deleted. But it would mean Columns UI is controlling that.

Also, a playlist can only have one lock. So that wouldn't work with an autoplaylist, for example.

Are there any third-party components that have that kind of functionality?

**Comment by grimes2** [comment]
foo_util and the JScript Smooth Playlist Manager. Most of my playlists are autoplaylists, so it doesn't make sense for me. Fortunately, last removed playlist can be restored.
